### ISSUE TITLE
Downloadbyquery api- Getting 202 status when passed without id

### ISSUE THREAD

**Issue by vasanth096** [datasetu/vermillion#302]
<img width="1025" alt="Screenshot 2021-09-13 at 1 57 51 PM" src="https://user-images.githubusercontent.com/69444787/133050392-d7b1aa4c-87ee-4126-b38a-a3049fc6dd48.png">

**Comment by Prabhu4452** [comment]
Resource Id is an optional query parameter here. So, it should be fine to proceed.

**Comment by vasanth096** [comment]
ok..so in that case would it download all the files contained by that access token with the query parameter?

**Comment by Prabhu4452** [comment]
> ok..so in that case would it download all the files contained by that access token with the query parameter?
@vasanth096  Nope.
It will download only when if,
Datasets w.r.t those query params fall under the consumer's authorised resource Id.

For ex- Below two cases
A) Consumer is not able to download datasets as a zip.
Query Params: Gender= male
Datasets directory is: /test-category/test-resource-2
Consumer's authorised resource Id is : /test-category/test-resource-1

Since, datasets fall in the Id test-resource-2 and consumer has only authorisation to Id test-resource-1. Thus, datasets will not be downloaded.

B) Consumer is able to download datasets as a zip.
Query Params: Gender= male
Datasets directory is: /test-category/test-resource-2
Consumer's authorised resource Id is : /test-category/test-resource-2

Since, datasets fall in the Id test-resource-2 and consumer also has authorisation to Id test-resource-2. Thus, datasets will not be downloaded.

**Comment by vasanth096** [comment]
Understood, works fine.
